
CREATE SCHEMA IF NOT EXISTS MONITORING;

CREATE TABLE IF NOT EXISTS MONITORING.SYSTEM (
  SYSTEM_ID UUID PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MONITORING.SYSTEM_PROPERTY (
  SYSTEM_ID UUID NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  VALUE VARCHAR(4096),
  FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MONITORING.EVENT (
  EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SYSTEM_ID UUID NOT NULL,
  TYPE VARCHAR(256) NOT NULL,
  TIME BIGINT NOT NULL,
  FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS MONITORING.EVENT_TIME ON MONITORING.EVENT (TYPE,TIME);

CREATE TABLE IF NOT EXISTS MONITORING.EVENT_PROPERTY (
  EVENT_ID BIGINT NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  VALUE VARCHAR(4096),
  REALVALUE REAL,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS MONITORING.EVENT_PROPERTY_STRING_VALUE ON MONITORING.EVENT_PROPERTY (NAME,VALUE);
CREATE INDEX IF NOT EXISTS MONITORING.EVENT_PROPERTY_REAL_VALUE ON MONITORING.EVENT_PROPERTY (NAME,REALVALUE);

CREATE TABLE IF NOT EXISTS MONITORING.COUNTER_VALUE (
  COUNTER_VALUE_ID IDENTITY,
  SYSTEM_ID UUID NOT NULL,
  METRIC_NAME VARCHAR(128) NOT NULL,
  TIME BIGINT NOT NULL,
  INCREMENT_VALUE INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS MONITORING.COUNTER_TIME ON MONITORING.COUNTER_VALUE (METRIC_NAME,TIME);

CREATE TABLE IF NOT EXISTS MONITORING.METRIC_VALUE (
  COUNTER_VALUE_ID IDENTITY,
  SYSTEM_ID UUID NOT NULL,
  METRIC_NAME VARCHAR(128) NOT NULL,
  TIME BIGINT NOT NULL,
  METRIC_VALUE REAL NOT NULL,
  FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS MONITORING.METRIC_TIME ON MONITORING.METRIC_VALUE (METRIC_NAME,TIME);
