
  CREATE SCHEMA IF NOT EXISTS MONITORING;

  CREATE TABLE IF NOT EXISTS MONITORING.SYSTEM (
    SYSTEM_ID UUID PRIMARY KEY
  );

  CREATE TABLE IF NOT EXISTS MONITORING.SYSTEM_PROPERTY (
    SYSTEM_ID UUID NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    VALUE VARCHAR(4096),
    FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS MONITORING.EVENT_TYPE (
    EVENT_TYPE_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_NAME VARCHAR2(256) NOT NULL
  );

  ALTER TABLE MONITORING.EVENT_TYPE ADD CONSTRAINT IF NOT EXISTS UNIQUE_EVENT_TYPE_NAME UNIQUE (EVENT_NAME);

  CREATE TABLE IF NOT EXISTS MONITORING.EVENT (
    EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE_ID SMALLINT NOT NULL,
    SYSTEM_ID UUID NOT NULL,
    TIME BIGINT NOT NULL,
    FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS MONITORING.EVENT_TIME ON MONITORING.EVENT (EVENT_ID,TIME);

  CREATE TABLE IF NOT EXISTS MONITORING.EVENT_PROPERTY (
    EVENT_ID BIGINT NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    VALUE VARCHAR(4096),
    REALVALUE REAL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS MONITORING.EVENT_PROPERTY_STRING_VALUE ON MONITORING.EVENT_PROPERTY (NAME,VALUE);
  CREATE INDEX IF NOT EXISTS MONITORING.EVENT_PROPERTY_REAL_VALUE ON MONITORING.EVENT_PROPERTY (NAME,REALVALUE);

  CREATE TABLE IF NOT EXISTS MONITORING.COUNTER (
    COUNTER_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    COUNTER_NAME VARCHAR(256) NOT NULL
  );

  ALTER TABLE MONITORING.COUNTER ADD CONSTRAINT IF NOT EXISTS  UNIQUE_COUNTER_NAME UNIQUE (COUNTER_NAME);

  CREATE TABLE IF NOT EXISTS MONITORING.COUNTER_VALUE (
    COUNTER_ID SMALLINT NOT NULL,
    SYSTEM_ID UUID NOT NULL,
    TIME BIGINT NOT NULL,
    INCREMENT_VALUE INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE,
    FOREIGN KEY (COUNTER_ID) REFERENCES MONITORING.COUNTER ON DELETE RESTRICT
  );

  CREATE INDEX IF NOT EXISTS MONITORING.COUNTER_TIME ON MONITORING.COUNTER_VALUE (COUNTER_ID,TIME,SYSTEM_ID);

  CREATE TABLE IF NOT EXISTS MONITORING.METRIC (
    METRIC_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    METRIC_NAME VARCHAR(256) NOT NULL
  );

  ALTER TABLE MONITORING.METRIC ADD CONSTRAINT IF NOT EXISTS UNIQUE_METRIC_NAME UNIQUE (METRIC_NAME);

  CREATE TABLE IF NOT EXISTS MONITORING.METRIC_VALUE (
    METRIC_ID SMALLINT NOT NULL,
    SYSTEM_ID UUID NOT NULL,
    TIME BIGINT NOT NULL,
    METRIC_VALUE REAL NOT NULL,
    FOREIGN KEY (SYSTEM_ID) REFERENCES MONITORING.SYSTEM ON DELETE CASCADE,
    FOREIGN KEY (METRIC_ID) REFERENCES MONITORING.METRIC ON DELETE RESTRICT
  );

  CREATE INDEX IF NOT EXISTS MONITORING.METRIC_TIME ON MONITORING.METRIC_VALUE (METRIC_ID,TIME,SYSTEM_ID);